/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test4;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class Login extends javax.swing.JFrame {
    Connection conn =null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    

//BufferedImage img;
    /**
     * Creates new form Login
     */
    public Login() throws IOException {
//        setLayout(new BorderLayout());
//    setContentPane(new JLabel(new ImageIcon("/home/ali/NetBeansProjects/back.jpg")));
//    setLayout(new FlowLayout());
       // this.img = ImageIO.read(new File("/home/ali/NetBeansProjects/back.jpg"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField_password = new javax.swing.JPasswordField();
        jComboBox_option = new javax.swing.JComboBox<>();
        jButton_login = new javax.swing.JButton();
        jButton_register = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText("WELCOME");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, 20, 135, 29);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(50, 70, 86, 30);
        jPanel3.add(jTextField_username);
        jTextField_username.setBounds(230, 70, 126, 30);
        jPanel3.add(jPasswordField_password);
        jPasswordField_password.setBounds(230, 130, 126, 30);

        jComboBox_option.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TPO", "Student" }));
        jComboBox_option.setOpaque(false);
        jComboBox_option.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_optionActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox_option);
        jComboBox_option.setBounds(130, 210, 150, 30);

        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_login);
        jButton_login.setBounds(10, 300, 175, 30);

        jButton_register.setText("Register(New User)");
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });
        jPanel3.add(jButton_register);
        jButton_register.setBounds(210, 300, 172, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(50, 130, 84, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/ali/Downloads/viitt2.png")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(70, 20, 260, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registerActionPerformed
        this.dispose();
        new Register().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_registerActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        conn = MySqlConnect.ConnectDB();
        String Sql="Select username,password,id from login where username =? and password=?";
        try{
            pst= conn.prepareStatement(Sql);
            pst.setString(1,jTextField_username.getText());
            pst.setString(2,jPasswordField_password.getText());
            rs=pst.executeQuery();
            if(rs.next())
            {
                //System.out.println(rs.getInt(3));
                if (jComboBox_option.getSelectedItem()=="TPO" )
                {
                    if(rs.getInt(3)==1){
                        JOptionPane.showMessageDialog(null, "Logged in as TPO");
                        this.dispose();
                        new TPO_file(jTextField_username.getText()).setVisible(true);
                    }
                    else
                    //JOptionPane.showMessageDialog(null, "You're not a TPO!");
                    JOptionPane.showMessageDialog(null,"You're not a TPO!","Error",JOptionPane.ERROR_MESSAGE);
                    jComboBox_option.requestFocusInWindow();
                }
                else if (jComboBox_option.getSelectedItem()=="Student")
                {
                    if(rs.getInt(3)==0)
                    { 
                        JOptionPane.showMessageDialog(null,"Logged in as Student");
                        this.dispose();
                        new student_file(jTextField_username.getText()).setVisible(true);
                    }
                    else
                    //JOptionPane.showMessageDialog(null, "You're not a Student!");
                    JOptionPane.showMessageDialog(null,"You're not a Student!","Error",JOptionPane.ERROR_MESSAGE);
                    jComboBox_option.requestFocusInWindow();

                }
                //JOptionPane.showMessageDialog(null,"welcome customer!");
                //  welcome w=new welcome();
                // w.setVisible(true);

            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Username or Password","Access Denied",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jComboBox_optionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_optionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_optionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_register;
    private javax.swing.JComboBox<String> jComboBox_option;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
