/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ali
 */
public class Register_schedule extends javax.swing.JFrame {

    Connection conn =null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    ResultSet rs1=null;
    ResultSet rs2=null;
    ResultSet rs3=null;
    
    
    Integer stud_id;
    Integer marks;
    Integer m1,m2,m3;
    Integer criteria;
    Integer sch_id;
    SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
    String date2 = null;
    public Register_schedule(Integer stu_id) {
        initComponents();
        setDefaultCloseOperation(Register_schedule.HIDE_ON_CLOSE);
        stud_id=stu_id;
       // JOptionPane.showMessageDialog(null, "Your ID is "+stud_id);
        conn = MySqlConnect.ConnectDB();
    }
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test5?autoReconnect=true&useSSL=false", "root","95752468aliasgar");
          
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
//               DefaultTableModel model = (DefaultTableModel)jTable_display.getModel();
//               model.setRowCount(0);
               
//               Show_Users_In_JTable();
             // Show_Login_In_JTable();
               //JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_sch_id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registration");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 20, 180, 29);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Schedule ID :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 90, 151, 17);

        jTextField_sch_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_sch_idActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_sch_id);
        jTextField_sch_id.setBounds(250, 80, 145, 30);

        jButton2.setText("Check Eligibility");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(250, 120, 145, 25);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(120, 170, 180, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/ali/Downloads/blue6.jpg")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, -150, 550, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_sch_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_sch_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_sch_idActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sch_id = Integer.parseInt(jTextField_sch_id.getText().toString());
       // JOptionPane.showMessageDialog(null,"Your Schedule ID is : "+sch_id);
        
       // String abc="SELECT TE from student where stu_id = '"+stud_id+"'";
        String query="SELECT FE,SE,TE from student where stu_id = '"+stud_id+"'";
        String abc1="SELECT criteria,sch_date from schedule where sch_id='"+sch_id+"'";
        try {
//            pst=conn.prepareStatement(abc);
//            rs=pst.executeQuery();
//            rs.next();
//            marks=rs.getInt(1);                 //taking the marks of the student
//            JOptionPane.showMessageDialog(null, "Your marks are "+marks);
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            rs.next();
            m1=rs.getInt(1);                 //taking the marks of the student
            m2=rs.getInt(2);
            m3=rs.getInt(3);
            
            
            //JOptionPane.showMessageDialog(null, "Your marks are "+marks);
           
        
        
           pst=conn.prepareStatement(abc1);
           rs1=pst.executeQuery(abc1);
           rs1.next();
           criteria=rs1.getInt(1);   
           date2=rs1.getDate(2).toString();          //taking the criteria of the schedule
           JOptionPane.showMessageDialog(null, "Your schedule criteria is : "+criteria);
           
           String compare="select stu_id,compare4(FE,SE,TE,'"+criteria+"') as Eligible from student where stu_id = '"+stud_id+"'";
           pst=conn.prepareStatement(compare);
           rs2=pst.executeQuery();
           rs2.next();
           marks=rs2.getInt(2);
           if(marks==1){
               JOptionPane.showMessageDialog(null, "You are eligible for the schedule");
           }
           else{
               JOptionPane.showMessageDialog(null,"You're not a eligible for the schedule!","Error",JOptionPane.ERROR_MESSAGE);
              // JOptionPane.showMessageDialog(null, "You're not eligible for the schedule!");
           }
               
        } catch (SQLException ex) {
            Logger.getLogger(Register_schedule.class.getName()).log(Level.SEVERE, null, ex);
        }

//            sch_id = Integer.parseInt(jTextField_sch_id.getText().toString());
//            JOptionPane.showMessageDialog(null,"Your Schedule ID is : "+sch_id);
            
        
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(marks==1){
            String query="Insert into appearing(stu_id,sch_id,appearing_date) values('"+stud_id+"','"+jTextField_sch_id.getText()+"','"+date2+"')";
        executeSQlQuery(query, "");
        JOptionPane.showMessageDialog(null, "Congratulations! You are registered for the schedule!");
        this.dispose();
        }
         else{
               JOptionPane.showMessageDialog(null, "You're not eligible for the schedule!");
           }
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Register_schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_sch_id;
    // End of variables declaration//GEN-END:variables
}
