/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ali
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    int year;
    String year1;
    public Report() {
        initComponents();
        setDefaultCloseOperation(Report.HIDE_ON_CLOSE);

        Show_Student_In_JTable(year1);
        
        
    }
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test5?autoReconnect=true&useSSL=false", "root","95752468aliasgar");
          
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
 public ArrayList<report1> getStudentList(String year)
   {
       ArrayList<report1> studentList = new ArrayList<report1>();
       Connection connection = getConnection();
       
       String query = "select count(cand_id),sch.co_name from candidate,company,sch where candidate.sch_id=sch.sch_id and sch.comp_id=company.comp_id and sch.acad_year='"+year+"' group by sch.co_name;";
       String query1 = "select count(cand_id),sch.co_name from candidate,company,sch where candidate.sch_id=sch.sch_id and sch.comp_id=company.comp_id group by sch.co_name;";

       Statement st;
       ResultSet rs=null;
       ResultSet rs1;
       try 
       {
           st = connection.createStatement();
           String abc="All";
           String cba=jComboBox1.getSelectedItem().toString();
          if(cba=="2010" || cba=="2011" || cba=="2012" || cba=="2013" || cba=="2014" ||cba=="2015" || cba=="2016" || cba=="2017"){
            rs = st.executeQuery(query);
          }
          else if (cba=="All"){
            rs = st.executeQuery(query1);
          }
           report1 user;
           while(rs.next())
           {
               user = new report1(rs.getInt("count(cand_id)"),rs.getString("sch.co_name"));//
               
               studentList.add(user);
           }
       } catch (Exception e) {
           e.printStackTrace();
       }
       return studentList;
   }
    public void Show_Student_In_JTable(String year1)
   {
       ArrayList<report1> list1 = getStudentList(year1);
       DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
       Object[] row = new Object[2];
       for(int i = 0; i < list1.size(); i++)
       {
           
           row[0] = list1.get(i).getcnt();
           row[1] = list1.get(i).getyear();
           
           
           model.addRow(row);
       }
    }


    
    /*                 FOR THE LAST TABLE          */
   
    
    
    
    /**************************************************************************************/


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_min = new javax.swing.JTextField();
        jTextField_max = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_total = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Report");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 110, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Total Students Recruited", "Company Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 400, 80);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(270, 70, 120, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Year : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 70, 90, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Min salary");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 250, 100, 17);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Max salary");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 250, 90, 17);
        jPanel1.add(jTextField_min);
        jTextField_min.setBounds(40, 280, 100, 30);
        jPanel1.add(jTextField_max);
        jTextField_max.setBounds(170, 280, 100, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "Persistent", "Infosys" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(240, 200, 110, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Company :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 200, 90, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Department :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 620, 120, 17);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Recruits");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(290, 250, 120, 17);
        jPanel1.add(jTextField_total);
        jTextField_total.setBounds(300, 279, 110, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("/home/ali/Downloads/blue6.jpg")); // NOI18N
        jLabel6.setText("Total Recruits");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 490, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //year=Integer.parseInt(jComboBox1.getSelectedItem().toString());
        year1=(jComboBox1.getSelectedItem().toString());
        Show_Student_In_JTable(year1);
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String comp;
        comp=jComboBox2.getSelectedItem().toString();
        String query="select min(package),max(package),count(cand_id) from candidate,company,sch where candidate.sch_id=sch.sch_id and company.comp_id=sch.comp_id and company.co_name='"+comp+"'group by company.comp_id;";
        String query1="select count(cand_id),sch.co_name from candidate,company,sch where candidate.sch_id=sch.sch_id and sch.comp_id=company.comp_id and sch.co_name='"+comp+"' group by sch.co_name;";
        Connection conn=getConnection();
    PreparedStatement ps;
        try {
            ps = conn.prepareStatement(query);
            ResultSet rs=ps.executeQuery();
            while(rs.next()) {
            jTextField_min.setText(rs.getString("min(package)").toString());
            jTextField_max.setText(rs.getString("max(package)").toString());
            jTextField_total.setText(rs.getString("count(cand_id)").toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_max;
    private javax.swing.JTextField jTextField_min;
    private javax.swing.JTextField jTextField_total;
    // End of variables declaration//GEN-END:variables
}
