/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test4;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ali
 */
public class student_register extends javax.swing.JFrame {

    /**
     * Creates new form student_register
     */
    int pid;
    String fname1;
    String email1;
    //Date d;
//    Calander c1;
    public student_register(String email) {
        initComponents();
        email1=email;
    }
    public student_register() {
        initComponents();
    }
     public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test5?autoReconnect=true&useSSL=false", "root","95752468aliasgar");
          // jdbc:mysql://localhost:3306/Peoples?autoReconnect=true&useSSL=false
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               //DefaultTableModel model = (DefaultTableModel)jTable_display.getModel();
               //model.setRowCount(0);
               
//               Show_Users_In_JTable();
             // Show_Login_In_JTable();
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
       }
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_dep = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Student Registration");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 20, 290, 29);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Academic Year:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 80, 123, 17);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        jPanel2.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(230, 69, 168, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Percentage");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(150, 120, 116, 22);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Year/Diploma : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 180, 170, 17);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Second Year :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 240, 120, 17);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(230, 170, 168, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(230, 230, 168, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Third Year :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 300, 93, 17);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5);
        jTextField5.setBounds(230, 290, 168, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(20, 340, 377, 18);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 380, 99, 17);

        jComboBox_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "Computer", "E&TC", "IT", "Mechanical" }));
        jComboBox_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_depActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_dep);
        jComboBox_dep.setBounds(230, 370, 168, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(160, 430, 100, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ali/Downloads/blue5.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 430, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_depActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());
        
        Connection conn=getConnection();
        String query4 = "SELECT p_id from person where email='"+email1+"'";
          ResultSet rs1;
          tpo_register obj = new tpo_register();
          Statement st1;
        try {
            st1 = conn.createStatement();
            rs1=st1.executeQuery(query4);
            rs1.next();
            pid=rs1.getInt(1);
           JOptionPane.showMessageDialog(null, rs1.getInt(1));
        
            //JOptionPane.showMessageDialog(null, rs1.getString(3));
        } catch (SQLException ex) {
            Logger.getLogger(tpo_register.class.getName()).log(Level.SEVERE, null, ex);
        }
        if((String)(jComboBox_dep.getSelectedItem())=="Civil")
        { 
            String query3 = "INSERT INTO `student`(`FE`,`SE`,`TE`,`academic_year`,`p_id`,`d_id`)VALUES('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"','"+date+"','"+pid+"','"+1002+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"Student Inserted");
                    
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="Computer")
        { 
            String query3 = "INSERT INTO `student`(`FE`,`SE`,`TE`,`academic_year`,`p_id`,`d_id`)VALUES('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"','"+date+"','"+pid+"','"+1001+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"Student Inserted");
                    
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="E&TC")
        { 
            String query3 = "INSERT INTO `student`(`FE`,`SE`,`TE`,`academic_year`,`p_id`,`d_id`)VALUES('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"','"+date+"','"+pid+"','"+1003+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"Student Inserted");
                    
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="IT")
        { 
            String query3 = "INSERT INTO `student`(`FE`,`SE`,`TE`,`academic_year`,`p_id`,`d_id`)VALUES('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"','"+date+"','"+pid+"','"+1004+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"Student Inserted");
                    
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="Mechanical")
        { 
            String query3 = "INSERT INTO `student`(`FE`,`SE`,`TE`,`academic_year`,`p_id`,`d_id`)VALUES('"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField5.getText()+"','"+date+"','"+pid+"','"+1005+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"Student Inserted");
                    
        }
        this.dispose();
        try {
            new Login().setVisible(true);
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(student_register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
