/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test4;
//import java.util.Date;
import datechooser.model.multiple.Period;
import java.io.IOException;
import java.sql.Date;
import java.util.Calendar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ali
 */
public class tpo_register extends javax.swing.JFrame {

    /**
     * Creates new form tpo_register
     */
    int pid;
    String fname1;
    String email1;
    Date d;
//    Calander c1;
    public tpo_register(String email) {
        initComponents();
        email1=email;
    }
    public tpo_register() {
        initComponents();
       // username1=username;
    }
    public Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/test5?autoReconnect=true&useSSL=false", "root","95752468aliasgar");
          
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
    public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               //DefaultTableModel model = (DefaultTableModel)jTable_display.getModel();
               //model.setRowCount(0);
               
//               Show_Users_In_JTable();
             // Show_Login_In_JTable();
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
       }
   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_desig = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField_salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_dep = new javax.swing.JComboBox<>();
        jButton_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TPO Registration");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 30, 226, 29);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designation : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 120, 109, 17);

        jComboBox_desig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TPO Co-ordinator", "Assistant Co-ordinator" }));
        jPanel2.add(jComboBox_desig);
        jComboBox_desig.setBounds(210, 100, 189, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Salary : ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(50, 180, 64, 17);
        jPanel2.add(jTextField_salary);
        jTextField_salary.setBounds(210, 170, 190, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Joining Date:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 240, 99, 17);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        jPanel2.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(210, 229, 190, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Department :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 300, 104, 17);

        jComboBox_dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "Computer", "E&TC", "IT", "Mechanical" }));
        jComboBox_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_depActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox_dep);
        jComboBox_dep.setBounds(210, 284, 190, 30);

        jButton_submit.setText("Submit");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_submit);
        jButton_submit.setBounds(140, 350, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ali/Downloads/blue5.jpg")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
       

//d.setDate(20);
SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
//dateChooser.getJCalendar().setPreferredSize(new Dimension(600, 500));
String date = formater.format(dateChooserCombo1.getSelectedDate().getTime());
String s=""+date;
String d1=""+dateChooserCombo1.getSelectedDate();
//formater.format(jXDatePicker1.getDate());
JOptionPane.showMessageDialog(null,s);



        Connection conn=getConnection();
        String query4 = "SELECT p_id from person where email='"+email1+"'";
          ResultSet rs1;
          tpo_register obj = new tpo_register();
          Statement st1;
        try {
            st1 = conn.createStatement();
            rs1=st1.executeQuery(query4);
            rs1.next();
            pid=rs1.getInt(1);
           JOptionPane.showMessageDialog(null, rs1.getInt(1));
        
            //JOptionPane.showMessageDialog(null, rs1.getString(3));
        } catch (SQLException ex) {
            Logger.getLogger(tpo_register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if((String)(jComboBox_dep.getSelectedItem())=="Civil")
        { //String query="INSERT INTO `TPO`(`d_id`) values('"+1005+"')";
            String query3 = "INSERT INTO `TPO`(`designation`,`salary`,`d_id`,`p_id`,`join_date`)VALUES('"+jComboBox_desig.getSelectedItem()+"','"+jTextField_salary.getText()+"','"+1002+"','"+pid+"','"+date+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"tpo Inserted");
                    
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="Computer"){
            String query3 = "INSERT INTO `TPO`(`designation`,`salary`,`d_id`,`p_id`,`join_date`)VALUES('"+jComboBox_desig.getSelectedItem()+"','"+jTextField_salary.getText()+"','"+1001+"','"+pid+"','"+date+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"tpo Inserted");
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="E&TC"){
            String query3 = "INSERT INTO `TPO`(`designation`,`salary`,`d_id`,`p_id`,`join_date`)VALUES('"+jComboBox_desig.getSelectedItem()+"','"+jTextField_salary.getText()+"','"+1003+"','"+pid+"','"+date+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"tpo Inserted");
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="IT"){
            String query3 = "INSERT INTO `TPO`(`designation`,`salary`,`d_id`,`p_id`,`join_date`)VALUES('"+jComboBox_desig.getSelectedItem()+"','"+jTextField_salary.getText()+"','"+1004+"','"+pid+"','"+date+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"tpo Inserted");
        }
        else if((String)(jComboBox_dep.getSelectedItem())=="Mechanical"){
            String query3 = "INSERT INTO `TPO`(`designation`,`salary`,`d_id`,`p_id`,`join_date`)VALUES('"+jComboBox_desig.getSelectedItem()+"','"+jTextField_salary.getText()+"','"+1005+"','"+pid+"','"+date+"')"; //+jXDatePicker1.getDate().toString()+"','"
            executeSQlQuery(query3,"tpo Inserted");
        }
      
      
        this.dispose();     
        try {
            new Login().setVisible(true);
            
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(tpo_register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jComboBox_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_depActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_depActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tpo_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tpo_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tpo_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tpo_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tpo_register().setVisible(true);
            }
        });
    }
    
    public void getDataFromLogin( int pid)
    {
        this.pid=pid;
        return;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JComboBox<String> jComboBox_dep;
    private javax.swing.JComboBox<String> jComboBox_desig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_salary;
    // End of variables declaration//GEN-END:variables
}
